postgres:
  image: postgres:15.2-alpine
  restart: always
  environment:
    POSTGRES_DB: nest-auth
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: admin
  ports:
    - '5432:5432'
  volumes:
    - docker-nest-postgres:/var/lib/postgresql/15/data