services:
  api:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - postgres
  postgres:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data

networks:
  - network
volumes:
  docker-nest-postgres: